github.com:
    git_protocol: https
    users:
        ThePixelExpert:
            oauth_token: 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
    user: ThePixelExpert
    oauth_token: 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
